{
  "packages": [
    "primitives/*/*",
    "apps/*"
  ],
  "catalog": {
    "eslint-plugin-ripple": "0.2.149",
    "prettier-plugin-ripple": "0.2.149",
    "ripple": "0.2.149",
    "vite-plugin-ripple": "0.2.149"
  }
}