{
  "packages": [
    "primitives/*/*",
    "apps/*"
  ],
  "catalog": {
    "eslint-plugin-ripple": "0.2.151",
    "prettier-plugin-ripple": "0.2.151",
    "ripple": "0.2.151",
    "vite-plugin-ripple": "0.2.151"
  }
}