{
  "packages": [
    "primitives/*/*",
    "apps/*"
  ],
  "catalog": {
    "eslint-plugin-ripple": "0.2.152",
    "prettier-plugin-ripple": "0.2.152",
    "ripple": "0.2.152",
    "vite-plugin-ripple": "0.2.152",
    "typescript-plugin-ripple" : "0.2.152"
  }
}